name: Generate badges

on:
  push:
    branches:
      - main

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install

      - name: Tests
        run: yarn test:badges

      - name: Generating coverage badges
        uses: ./
        with:
          branches: '*'
