name: Generate badges on custom branch

on:
  push:
    branches:
      - main

jobs:
  generate-badges-on-custom-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Installing dependencies
        run: yarn install

      - name: Delete remote badges branch
        run: git push origin --delete badges

      - name: Create badges branch
        run: git checkout -b badges

      - name: Tests
        run: yarn test-ci

      - name: Generating coverage badges
        uses: ./
        with:
          branches: '*'
          target-branch: badges

      - name: Push badges branch
        run: git push origin badges
